image: openjdk:8-jdk-slim
stages:
  - test
  - deploy

variables:
  GRADLE_ARGS: --no-daemon --stacktrace
  DEBIAN_FRONTEND: noninteractive

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - apt-get update &&  apt-get install -y patch

.tests:
  stage: test
  script: ./gradlew ${GRADLE_ARGS} clean deploy
  artifacts:
    paths:
      - build/reports/tests/
    when: on_failure

tests:jdk-8:
  extends: .tests

tests:jdk-11:
  extends: .tests
  image: openjdk:11-jdk-slim

tests:macos:
  extends: .tests
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  tags:
    - macos

tests:windows64:
  extends: .tests
  before_script: []
  script: gradlew.bat %GRADLE_ARGS% clean deploy
  tags:
    - prob
    - win64
  allow_failure: true
  when: manual

publish:
  stage: deploy
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - apt-get update &&  apt-get install -y patch
    - openssl aes-256-cbc -pass "env:ENCRYPTION_PASSWORD" -d -a -md md5 -in secring.gpg.enc       -out secring.gpg 
    - openssl aes-256-cbc -pass "env:ENCRYPTION_PASSWORD" -d -a -md md5 -in pubring.gpg.enc       -out pubring.gpg
    - openssl aes-256-cbc -pass "env:ENCRYPTION_PASSWORD" -d -a -md md5 -in gradle.properties.enc -out gradle.properties
  script:
    - ./gradlew ${GRADLE_ARGS} uploadArchives
  only: 
    - master 
    - develop
