package de.prob.voparser;

public enum VOType {
	RELOAD, RESET, TRACE_REPLAY, STATE_SPACE_VISUALIZATION,
	TRACE_VISUALIZATION, COVERAGE, TRACE_COVERAGE,
	MODEL_CHECKING_GOAL, MODEL_CHECKING_INV, MODEL_CHECKING_INV_COMPLETE,
	LTL_MODEL_CHECKING, LTL_CURRENT, LTL_CURRENT_GOAL
}
