package de.prob.voparser;

public enum VTType {
	RELOAD, RESET, STATIC,
	TRACE_REPLAY, TRACE_VISUALIZATION, TRACE_COVERAGE,
	STATE_SPACE_VISUALIZATION, STATE_SPACE_COVERAGE,
	SEARCHING_GOAL, CHECKING_PROP, EXPLORING_STATE_SPACE
}
