package de.prob.voparser;

public enum VTType {
	RELOAD, RESET, STATIC,
	TRACE_REPLAY, TRACE_VISUALIZATION, TRACE_COVERAGE,
	STATE_SPACE_VISUALIZATION, STATE_SPACE_COVERAGE,
	MODEL_CHECKING_GOAL, MODEL_CHECKING_PROP, MODEL_CHECKING_COMPLETE
}
