plugins {
	id("jacoco")
	id("java-library")

	id("de.hhu.stups.sablecc")
}

description = "ProB's parser for classical B"

dependencies {
	sableCC(rootProject.sableCCDependency)
	api(rootProject.sableCCRuntimeDependency)
	api project(":prologlib")
	api project(":parserbase")
}

final firstLineOfProcessOutput = {ExecOutput execOutput ->
	return execOutput.standardOutput.asText.map {it.split("\n")[0]}
}

tasks.named("processResources", ProcessResources) {
	inputs.property("version", project.version)
	inputs.property("currentGitCommit", firstLineOfProcessOutput(providers.exec {
		executable = "git"
		args = ["rev-parse", "HEAD"]
	}))

	filesMatching("de/be4/classicalb/core/parser/build.properties") {
		expand(version: inputs.properties["version"], git: inputs.properties["currentGitCommit"])
	}
}

rootProject.setupTestReport(project, ["de.be4.classicalb.core.parser", "de.be4.classicalb.core.preparser"])
