# this is just a simple reminder on what kind of gradle tasks that can be run
parseable:
	gradle test --tests de.be4.classicalb.core.parser.ParsableMachineTest --info
test2:
	gradle test --tests de.be4.classicalb.core.parser.ParseableButProblematicOnWindowsUnixLF --info
rules:
	gradle test --tests de.be4.classicalb.core.parser.rules.RulesMachineFilesTest --info
tokens:
	gradle test --tests de.be4.classicalb.core.parser.SyntaxErrorsDetectedOnTokenStreamTest --info
defs:
	gradle test --tests de.be4.classicalb.core.parser.definitions.DefinitionFilesTest --info
expr:
	gradle test --tests de.be4.classicalb.core.parser.ExpressionTest --info
comments:
	gradle test --tests de.be4.classicalb.core.parser.CommentsTest --info
