# this is just a simple reminder on what kind of gradle tasks that can be run
parseable:
	gradle test --tests de.be4.classicalb.core.parser.ParsableMachineTest --info
test2:
	gradle test --tests de.be4.classicalb.core.parser.ParseableButProblematicOnWindowsUnixLF --info
rules:
	gradle test --tests de.be4.classicalb.core.parser.rules.RulesMachineFilesTest --info